/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uta.interfaces;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author pc
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public void visualizarReporteSexo(){
        jdskPrincipal.removeAll();
        jdskPrincipal.repaint();
        //ReporteSexo s = new ReporteSexo();
//        jdskPrincipal.add(s);
        try {
//            s.setVisible(true);
        } catch (Exception ex) {
        }
//        s.show();
    }
   
    public void visualizarReporteEstudiante(){
        jdskPrincipal.removeAll();
        jdskPrincipal.repaint();
      //  ReporteEstudiante e = new ReporteEstudiante();
//        jdskPrincipal.add(e);
        try {
//            e.setVisible(true);
        } catch (Exception ex) {
        }
//        e.show();
    }
    
    public void visualizarReporteCurso(){
        jdskPrincipal.removeAll();
        jdskPrincipal.repaint();
        ReportePasajero r = new ReportePasajero();
        jdskPrincipal.add(r);
        try {
           r.setVisible(true);
        } catch (Exception ex) {
        }
        r.show();
    }
    
    public void visualizarIntEstudiantes() {
        jdskPrincipal.removeAll();
        jdskPrincipal.repaint();
        agregarPasajero e = new agregarPasajero();
        jdskPrincipal.add(e);
        try {
            e.setVisible(true);
        } catch (Exception ex) {
        }
        e.show();
    }
    
    public void visualizarIntUsuarios(){
        jdskPrincipal.removeAll();
        jdskPrincipal.repaint();
        registroUsuarios u = new registroUsuarios();
        jdskPrincipal.add(u);
        try {
            u.setVisible(true);
        } catch (Exception ex) {
        }
        u.show();
    }
    
    public void visualizarIntCurso(){
        jdskPrincipal.removeAll();
        jdskPrincipal.repaint();
        insertarUnidad c = new insertarUnidad();
        jdskPrincipal.add(c);
        try {
            c.setVisible(true);
        } catch (Exception ex) {
        }
        c.show();
    }

    public void interfazAdministrador() {
        jmenuInterfaces.setEnabled(true);
        jmenuReportes.setEnabled(true);
    }

    public void interfazSecretaria() {
        jmenuInterfaces.setEnabled(true);
        jmenuReportes.setEnabled(false);
        jmniCursos.setEnabled(false);
        jmniUsuarios.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jdskPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuInterfaces = new javax.swing.JMenu();
        jmniEstudiantes = new javax.swing.JMenuItem();
        jmniUsuarios = new javax.swing.JMenuItem();
        jmniCursos = new javax.swing.JMenuItem();
        jmenuReportes = new javax.swing.JMenu();
        jmniReporteCurso = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdskPrincipal.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jdskPrincipalLayout = new javax.swing.GroupLayout(jdskPrincipal);
        jdskPrincipal.setLayout(jdskPrincipalLayout);
        jdskPrincipalLayout.setHorizontalGroup(
            jdskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        jdskPrincipalLayout.setVerticalGroup(
            jdskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        jmenuInterfaces.setText("INTERFACES");

        jmniEstudiantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmniEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Estudiante.jpg"))); // NOI18N
        jmniEstudiantes.setText("PASAJEROS");
        jmniEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniEstudiantesActionPerformed(evt);
            }
        });
        jmenuInterfaces.add(jmniEstudiantes);

        jmniUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmniUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Usuario.jpeg"))); // NOI18N
        jmniUsuarios.setText("CUENTAS");
        jmniUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniUsuariosActionPerformed(evt);
            }
        });
        jmenuInterfaces.add(jmniUsuarios);

        jmniCursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmniCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Curso.jpeg"))); // NOI18N
        jmniCursos.setText("UNIDADES");
        jmniCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniCursosActionPerformed(evt);
            }
        });
        jmenuInterfaces.add(jmniCursos);

        jMenuBar1.add(jmenuInterfaces);

        jmenuReportes.setText("REPORTE");

        jmniReporteCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jmniReporteCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reporte.jpeg"))); // NOI18N
        jmniReporteCurso.setText("REPORTE DE PASAJEROS");
        jmniReporteCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniReporteCursoActionPerformed(evt);
            }
        });
        jmenuReportes.add(jmniReporteCurso);

        jMenuBar1.add(jmenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdskPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmniEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniEstudiantesActionPerformed
        // TODO add your handling code here:
        visualizarIntEstudiantes();
    }//GEN-LAST:event_jmniEstudiantesActionPerformed

    private void jmniReporteCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniReporteCursoActionPerformed
        // TODO add your handling code here:
        visualizarReporteCurso();
    }//GEN-LAST:event_jmniReporteCursoActionPerformed

    private void jmniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniUsuariosActionPerformed
        // TODO add your handling code here:
        visualizarIntUsuarios();
    }//GEN-LAST:event_jmniUsuariosActionPerformed

    private void jmniCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniCursosActionPerformed
        // TODO add your handling code here:
        visualizarIntCurso();
    }//GEN-LAST:event_jmniCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdskPrincipal;
    private javax.swing.JMenu jmenuInterfaces;
    private javax.swing.JMenu jmenuReportes;
    private javax.swing.JMenuItem jmniCursos;
    private javax.swing.JMenuItem jmniEstudiantes;
    private javax.swing.JMenuItem jmniReporteCurso;
    private javax.swing.JMenuItem jmniUsuarios;
    // End of variables declaration//GEN-END:variables
}
